#  Config file.
#
#  Author: Dana Clemmer
#  File: application.yml
#  Date: 10/25/2021

#server:
#  port: 3306

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adventures
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${USER}
    password: ${PASS}

  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init.mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

